# Generated by Django 5.0.1 on 2025-02-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('Alumno_RUT', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Alumno_Nombre', models.CharField(max_length=50)),
                ('Alumno_Apellido_Pat', models.CharField(max_length=50)),
                ('Alumno_Apellido_Mat', models.CharField(max_length=50)),
                ('Alumno_Curso', models.CharField(max_length=10)),
                ('Alumno_TEA', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_ID', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('Familia_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Apoderado_RUT', models.CharField(max_length=8)),
                ('Alumno_RUT', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('lugar_ID', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('tipo_ID', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('trabajador_ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('trabajador_nombre', models.CharField(max_length=50)),
                ('trabajador_apellido', models.CharField(max_length=50)),
                ('trabajador_apellido2', models.CharField(max_length=50, null=True)),
                ('trabajador_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('Apoderado_RUT', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Apoderado_Nombre', models.CharField(max_length=50)),
                ('Apoderado_Apellido_Pat', models.CharField(max_length=50)),
                ('Apoderado_Apellido_Mat', models.CharField(max_length=50)),
                ('Apoderado_Mail', models.CharField(max_length=50)),
                ('Apoderado_Observacion', models.CharField(max_length=200, null=True)),
                ('Apoderado_Activo', models.BooleanField()),
                ('Hijo_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijo1_set', to='reconocimiento.alumno')),
                ('Hijo_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijo2_set', to='reconocimiento.alumno')),
                ('Hijo_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijo3_set', to='reconocimiento.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('visita_ID', models.AutoField(primary_key=True, serialize=False)),
                ('visita_rut', models.CharField(max_length=8)),
                ('visita_nombre', models.CharField(max_length=50)),
                ('visita_apellido_1', models.CharField(max_length=50)),
                ('visita_apellido_2', models.CharField(max_length=50, null=True)),
                ('visita_observacion', models.CharField(max_length=200, null=True)),
                ('visita_fecha_llegada', models.DateTimeField()),
                ('visita_fecha_salida', models.DateTimeField(null=True)),
                ('visita_activo', models.BooleanField(null=True)),
                ('empresa_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconocimiento.empresa')),
                ('lugar_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimiento.lugar')),
                ('tipo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimiento.tipo')),
                ('trabajador_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconocimiento.trabajador')),
            ],
        ),
    ]
